/**
 * Demo dataset used when VITE_USE_MOCK === "true".
 *
 * Every record matches the real public.emails row shape exactly (types.ts /
 * backend/schema.sql). These are hand-written fixtures in the style of the
 * organizer's participant data — this file contains NO verification logic:
 * `status`, `has_defect` and `defect_fields` are fixed values standing in for
 * what the backend would have decided, never something computed here.
 */
import type { AttachmentRecord, Batch, EmailRecord, ShipmentFields } from "./types";

function fields(partial: Partial<ShipmentFields>): ShipmentFields {
  return {
    shipper: null,
    consignee: null,
    notify_party: null,
    port_of_loading: null,
    port_of_discharge: null,
    container_count: null,
    gross_weight_kg: null,
    ...partial,
  };
}

const T = (offsetMinutes: number): string =>
  new Date(Date.UTC(2026, 8, 21, 9, 0, 0) - offsetMinutes * 60_000).toISOString();

interface Seed {
  record: EmailRecord;
  attachments: Array<{
    original_filename: string;
    content_type: string | null;
    size_bytes: number | null;
    doc_type: AttachmentRecord["doc_type"];
  }>;
}

const SEEDS: Seed[] = [
  {
    // completed + MISMATCH, 2 fields — the reference sample from the brief.
    record: {
      email_id: "email_004",
      sender: "docs@vitalsolutions.sg",
      subject: "REQUEST BL DRAFT _ PO 26067_ COATED IVORY BOARD__138MT",
      body: "Hi Mitchelle,\n\nAttached are the SI and draft BL for OC 5ALT-01226 (COATED IVORY BOARD). Please check the details and confirm.\n\nBest Regards,\nDeswita Elvyani\nShipping Documentation\nAPRIL Fine Paper Trading (Middle East) Fze\n#813, 4 EA, Dubai Airport Free Zone\nP.O. Box : 293775, Dubai, United Arab Emirates",
      source_attachments: ["attachments/email_004_SI.txt", "attachments/email_004_BL.txt"],
      category: "BL_COMPARISON",
      status: "MISMATCH",
      si: fields({
        shipper: "APRIL FAR EAST (M) SDN BHD",
        consignee: "EAST BRIGHT FZ-LLC",
        notify_party: "EAST BRIGHT FZ-LLC",
        port_of_loading: "NANTONG, CHINA (CNNTG)",
        port_of_discharge: "KARACHI, PAKISTAN (PKKHI)",
        container_count: 6,
        gross_weight_kg: 131058,
      }),
      bl: fields({
        shipper: "APRIL FAR EAST (M) SDN BHD",
        consignee: "UAB NOVAKOPA",
        notify_party: "UAB NOVAKOPA",
        port_of_loading: "NANTONG, CHINA (CNNTG)",
        port_of_discharge: "KARACHI, PAKISTAN (PKKHI)",
        container_count: 6,
        gross_weight_kg: 131058,
      }),
      defect_fields: ["consignee", "notify_party"],
      has_defect: true,
      review_reason: null,
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(2880),
      updated_at: T(35),
    },
    attachments: [
      { original_filename: "email_004_SI.txt", content_type: "text/plain", size_bytes: 3142, doc_type: "SI" },
      { original_filename: "email_004_BL.txt", content_type: "text/plain", size_bytes: 2988, doc_type: "BL" },
    ],
  },
  {
    // completed + MISMATCH, 1 field (container_count 3 vs 4).
    record: {
      email_id: "email_011",
      sender: "exports@sinarmas-pulp.co.id",
      subject: "Draft BL check — OC 7RTX-00841 / BLEACHED KRAFT / 3x40HC",
      body: "Dear Mitchelle,\n\nPlease find the shipping instruction and the carrier's draft bill of lading for OC 7RTX-00841.\n\nKindly revert with confirmation before the cut-off on Thursday.\n\nRegards,\nBudi Hartono\nExport Documentation\nPT Sinarmas Pulp & Paper",
      source_attachments: ["attachments/email_011_SI.pdf", "attachments/email_011_BL.pdf"],
      category: "BL_COMPARISON",
      status: "MISMATCH",
      si: fields({
        shipper: "PT SINARMAS PULP & PAPER",
        consignee: "HANSOL PAPER CO., LTD",
        notify_party: "HANSOL PAPER CO., LTD",
        port_of_loading: "TANJUNG PRIOK, INDONESIA (IDTPP)",
        port_of_discharge: "BUSAN, KOREA (KRPUS)",
        container_count: 3,
        gross_weight_kg: 68420.5,
      }),
      bl: fields({
        shipper: "PT SINARMAS PULP & PAPER",
        consignee: "HANSOL PAPER CO., LTD",
        notify_party: "HANSOL PAPER CO., LTD",
        port_of_loading: "TANJUNG PRIOK, INDONESIA (IDTPP)",
        port_of_discharge: "BUSAN, KOREA (KRPUS)",
        container_count: 4,
        gross_weight_kg: 68420.5,
      }),
      defect_fields: ["container_count"],
      has_defect: true,
      review_reason: null,
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(4100),
      updated_at: T(120),
    },
    attachments: [
      { original_filename: "email_011_SI.pdf", content_type: "application/pdf", size_bytes: 184320, doc_type: "SI" },
      { original_filename: "email_011_BL.pdf", content_type: "application/pdf", size_bytes: 201440, doc_type: "BL" },
    ],
  },
  {
    // completed + MISMATCH, long multi-line addresses.
    record: {
      email_id: "email_019",
      sender: "documentation@pacificrimforwarding.com.au",
      subject: "BL draft for verification — OC 2QQA-03317 — MERINO WOOL TOPS — 2x20GP",
      body: "Good afternoon,\n\nThe SI and the draft BL for OC 2QQA-03317 are attached. The consignee address was updated last week, so please pay particular attention to it.\n\nKind regards,\nAlison Whitcombe\nPacific Rim Forwarding Pty Ltd\nLevel 9, 200 Mary Street\nBrisbane QLD 4000, Australia",
      source_attachments: ["attachments/email_019_SI.docx", "attachments/email_019_BL.pdf"],
      category: "BL_COMPARISON",
      status: "MISMATCH",
      si: fields({
        shipper:
          "AUSTRALIAN WOOL EXCHANGE PTY LTD\nUnit 14, 21-25 Bowden Street\nAlexandria NSW 2015\nAustralia",
        consignee:
          "BIELLA FILATI INDUSTRIALE S.P.A.\nVia Carso 118/A\n13900 Biella (BI)\nItaly\nVAT IT01994820021",
        notify_party:
          "BIELLA FILATI INDUSTRIALE S.P.A.\nVia Carso 118/A\n13900 Biella (BI)\nItaly\nAttn: Sig. Renzo Pavan",
        port_of_loading: "SYDNEY, AUSTRALIA (AUSYD)",
        port_of_discharge: "GENOA, ITALY (ITGOA)",
        container_count: 2,
        gross_weight_kg: 41235,
      }),
      bl: fields({
        shipper:
          "AUSTRALIAN WOOL EXCHANGE PTY LTD\nUnit 14, 21-25 Bowden Street\nAlexandria NSW 2015\nAustralia",
        consignee:
          "BIELLA FILATI INDUSTRIALE S.P.A.\nVia Carso 118/A\n13900 Biella (BI)\nItaly\nVAT IT01994820021",
        notify_party:
          "LANIFICIO CERRUTI S.P.A.\nVia Cernaia 40\n13900 Biella (BI)\nItaly",
        port_of_loading: "SYDNEY, AUSTRALIA (AUSYD)",
        port_of_discharge: "LA SPEZIA, ITALY (ITSPE)",
        container_count: 2,
        gross_weight_kg: 41235,
      }),
      defect_fields: ["notify_party", "port_of_discharge"],
      has_defect: true,
      review_reason: null,
      decided_by: "llm",
      notes: "Notify party and discharge port differ between the instruction and the draft.",
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(5600),
      updated_at: T(300),
    },
    attachments: [
      {
        original_filename: "email_019_SI.docx",
        content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        size_bytes: 27310,
        doc_type: "SI",
      },
      { original_filename: "email_019_BL.pdf", content_type: "application/pdf", size_bytes: 312890, doc_type: "BL" },
    ],
  },
  {
    // completed + OK.
    record: {
      email_id: "email_002",
      sender: "shipping.docs@evergreenpaper.com.tw",
      subject: "SI + draft BL — OC 3KLM-00218 — UNCOATED WOODFREE — please confirm",
      body: "Hi Mitchelle,\n\nAttached is the shipping instruction together with the carrier's draft bill of lading for OC 3KLM-00218.\n\nPlease confirm if everything is in order.\n\nThanks,\nChen Yu-Ting\nEvergreen Paper Industrial Co., Ltd.",
      source_attachments: ["attachments/email_002_SI.txt", "attachments/email_002_BL.txt"],
      category: "BL_COMPARISON",
      status: "OK",
      si: fields({
        shipper: "EVERGREEN PAPER INDUSTRIAL CO., LTD",
        consignee: "NORDIC PAPER TRADING AB",
        notify_party: "NORDIC PAPER TRADING AB",
        port_of_loading: "KAOHSIUNG, TAIWAN (TWKHH)",
        port_of_discharge: "GOTHENBURG, SWEDEN (SEGOT)",
        container_count: 4,
        gross_weight_kg: 87640,
      }),
      bl: fields({
        shipper: "EVERGREEN PAPER INDUSTRIAL CO LTD",
        consignee: "NORDIC PAPER TRADING AB",
        notify_party: "NORDIC PAPER TRADING AB",
        port_of_loading: "KAOHSIUNG, TAIWAN (TWKHH)",
        port_of_discharge: "GOTHENBURG, SWEDEN (SEGOT)",
        container_count: 4,
        gross_weight_kg: 87640,
      }),
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "rule",
      notes: "No mismatch detected.",
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(1400),
      updated_at: T(58),
    },
    attachments: [
      { original_filename: "email_002_SI.txt", content_type: "text/plain", size_bytes: 2740, doc_type: "SI" },
      { original_filename: "email_002_BL.txt", content_type: "text/plain", size_bytes: 2610, doc_type: "BL" },
    ],
  },
  {
    // completed + OK, coded subject line.
    record: {
      email_id: "email_027",
      sender: "aie.docs@carriersolutions.hk",
      subject: "AIE - PODJEA - MAEU(263814592) - OC 9WTY-00455 - INV 4471182 - VITAL SOLUTIONS - CFR",
      body: "Documents for the referenced shipment are attached.\n\nSI and BL both issued 18 September. No amendments outstanding.\n\nCarrier Solutions (HK) Limited\nDocumentation Desk",
      source_attachments: ["attachments/email_027_SI.xlsx", "attachments/email_027_BL.pdf"],
      category: "BL_COMPARISON",
      status: "OK",
      si: fields({
        shipper: "VITAL SOLUTIONS FZE",
        consignee: "JEBEL ALI TRADING DMCC",
        notify_party: "JEBEL ALI TRADING DMCC",
        port_of_loading: "HONG KONG (HKHKG)",
        port_of_discharge: "JEBEL ALI, UAE (AEJEA)",
        container_count: 1,
        gross_weight_kg: 21980,
      }),
      bl: fields({
        shipper: "VITAL SOLUTIONS FZE",
        consignee: "JEBEL ALI TRADING DMCC",
        notify_party: "JEBEL ALI TRADING DMCC",
        port_of_loading: "HONG KONG (HKHKG)",
        port_of_discharge: "JEBEL ALI, UAE (AEJEA)",
        container_count: 1,
        gross_weight_kg: 21980,
      }),
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "rule",
      notes: "No mismatch detected.",
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(6900),
      updated_at: T(410),
    },
    attachments: [
      {
        original_filename: "email_027_SI.xlsx",
        content_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        size_bytes: 18944,
        doc_type: "SI",
      },
      { original_filename: "email_027_BL.pdf", content_type: "application/pdf", size_bytes: 245118, doc_type: "BL" },
    ],
  },
  {
    // completed + OK, already reviewed by a human.
    record: {
      email_id: "email_033",
      sender: "logistics@borealisforest.fi",
      subject: "Corrected SI attached — OC 5HHD-01902 — BIRCH PULP — 5x40HC",
      body: "Hello,\n\nFollowing our call, here is the corrected shipping instruction along with the draft BL.\n\nThe gross weight on the original SI was a typing error.\n\nBest regards,\nMarkku Laaksonen\nBorealis Forest Products Oy",
      source_attachments: ["attachments/email_033_SI.pdf", "attachments/email_033_BL.pdf"],
      category: "BL_COMPARISON",
      status: "OK",
      si: fields({
        shipper: "BOREALIS FOREST PRODUCTS OY",
        consignee: "SHANDONG CHENMING PAPER HOLDINGS LTD",
        notify_party: "SHANDONG CHENMING PAPER HOLDINGS LTD",
        port_of_loading: "KOTKA, FINLAND (FIKTK)",
        port_of_discharge: "QINGDAO, CHINA (CNTAO)",
        container_count: 5,
        gross_weight_kg: 112750,
      }),
      bl: fields({
        shipper: "BOREALIS FOREST PRODUCTS OY",
        consignee: "SHANDONG CHENMING PAPER HOLDINGS LTD",
        notify_party: "SHANDONG CHENMING PAPER HOLDINGS LTD",
        port_of_loading: "KOTKA, FINLAND (FIKTK)",
        port_of_discharge: "QINGDAO, CHINA (CNTAO)",
        container_count: 5,
        gross_weight_kg: 112750,
      }),
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "rule",
      notes: "No mismatch detected.",
      processing_status: "completed",
      retry_count: 1,
      last_error: null,
      reviewed_at: T(600),
      reviewer_notes: "Gross weight confirmed against the packing list. Corrected SI value entered.",
      created_at: T(8200),
      updated_at: T(600),
    },
    attachments: [
      { original_filename: "email_033_SI.pdf", content_type: "application/pdf", size_bytes: 166002, doc_type: "SI" },
      { original_filename: "email_033_BL.pdf", content_type: "application/pdf", size_bytes: 174551, doc_type: "BL" },
    ],
  },
  {
    // NEEDS_REVIEW — missing_attachment.
    record: {
      email_id: "email_007",
      sender: "mira.dahlan@oceanlinkshipping.my",
      subject: "BL draft for checking — OC 8PLQ-00733 — please compare with SI",
      body: "Hi,\n\nPlease check the attached draft BL against the shipping instruction you already hold for OC 8PLQ-00733.\n\nRegards,\nMira Dahlan\nOcean Link Shipping Sdn Bhd",
      source_attachments: ["attachments/email_007_BL.pdf"],
      category: "BL_COMPARISON",
      status: "NEEDS_REVIEW",
      si: null,
      bl: fields({
        shipper: "OCEAN LINK SHIPPING SDN BHD",
        consignee: "PT MULTI BINTANG NIAGA",
        notify_party: null,
        port_of_loading: "PORT KLANG, MALAYSIA (MYPKG)",
        port_of_discharge: "SURABAYA, INDONESIA (IDSUB)",
        container_count: 2,
        gross_weight_kg: null,
      }),
      defect_fields: [],
      has_defect: false,
      review_reason: "missing_attachment",
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(3300),
      updated_at: T(90),
    },
    attachments: [
      { original_filename: "email_007_BL.pdf", content_type: "application/pdf", size_bytes: 198770, doc_type: "BL" },
    ],
  },
  {
    // NEEDS_REVIEW — unreadable.
    record: {
      email_id: "email_014",
      sender: "docs@transglobalfreight.ae",
      subject: "SI & BL — OC 4NNB-02214 — SODA ASH DENSE — scanned copies",
      body: "Dear Mitchelle,\n\nScanned copies of the SI and BL are attached for OC 4NNB-02214.\n\nApologies for the quality, the originals were faxed to us.\n\nThanks,\nRashid Al Marri\nTransGlobal Freight LLC",
      source_attachments: ["attachments/email_014_SI.pdf", "attachments/email_014_BL.pdf"],
      category: "BL_COMPARISON",
      status: "NEEDS_REVIEW",
      si: fields({
        shipper: "TRANSGLOBAL FREIGHT LLC",
        consignee: null,
        notify_party: null,
        port_of_loading: "JEBEL ALI, UAE (AEJEA)",
        port_of_discharge: null,
        container_count: null,
        gross_weight_kg: null,
      }),
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: "unreadable",
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(4700),
      updated_at: T(210),
    },
    attachments: [
      { original_filename: "email_014_SI.pdf", content_type: "application/pdf", size_bytes: 1442310, doc_type: "SI" },
      { original_filename: "email_014_BL.pdf", content_type: "application/pdf", size_bytes: 1688204, doc_type: "UNREADABLE" },
    ],
  },
  {
    // NEEDS_REVIEW — wrong_doc_type.
    record: {
      email_id: "email_021",
      sender: "accounts@harbourpointlogistics.co.nz",
      subject: "Documents for OC 6DDZ-01140 — CHILLED LAMB — 1x40RH",
      body: "Hi Mitchelle,\n\nAttaching the paperwork for OC 6DDZ-01140.\n\nLet me know if you need anything else.\n\nCheers,\nPeter Nguyen\nHarbourpoint Logistics Ltd",
      source_attachments: ["attachments/email_021_SI.txt", "attachments/email_021_INVOICE.pdf"],
      category: "BL_COMPARISON",
      status: "NEEDS_REVIEW",
      si: fields({
        shipper: "HARBOURPOINT LOGISTICS LTD",
        consignee: "AL RAWABI MEAT TRADING LLC",
        notify_party: "AL RAWABI MEAT TRADING LLC",
        port_of_loading: "AUCKLAND, NEW ZEALAND (NZAKL)",
        port_of_discharge: "JEBEL ALI, UAE (AEJEA)",
        container_count: 1,
        gross_weight_kg: 24100,
      }),
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: "wrong_doc_type",
      decided_by: "llm",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(5100),
      updated_at: T(255),
    },
    attachments: [
      { original_filename: "email_021_SI.txt", content_type: "text/plain", size_bytes: 2312, doc_type: "SI" },
      { original_filename: "email_021_INVOICE.pdf", content_type: "application/pdf", size_bytes: 88120, doc_type: "OTHER" },
    ],
  },
  {
    // NEEDS_REVIEW — missing_value.
    record: {
      email_id: "email_038",
      sender: "shipping@andeancargo.cl",
      subject: "SI / BL check requested — OC 1FGH-00907 — FRESH BLUEBERRIES",
      body: "Estimada Mitchelle,\n\nAdjunto la instruccion de embarque y el borrador del BL para OC 1FGH-00907.\n\nSaludos cordiales,\nCarolina Munoz\nAndean Cargo SpA",
      source_attachments: ["attachments/email_038_SI.xlsx", "attachments/email_038_BL.docx"],
      category: "BL_COMPARISON",
      status: "NEEDS_REVIEW",
      si: fields({
        shipper: "ANDEAN CARGO SPA",
        consignee: "FRESHCO PRODUCE BV",
        notify_party: "FRESHCO PRODUCE BV",
        port_of_loading: "VALPARAISO, CHILE (CLVAP)",
        port_of_discharge: "ROTTERDAM, NETHERLANDS (NLRTM)",
        container_count: 2,
        gross_weight_kg: null,
      }),
      bl: fields({
        shipper: "ANDEAN CARGO SPA",
        consignee: "FRESHCO PRODUCE BV",
        notify_party: null,
        port_of_loading: "VALPARAISO, CHILE (CLVAP)",
        port_of_discharge: "ROTTERDAM, NETHERLANDS (NLRTM)",
        container_count: 2,
        gross_weight_kg: 39880,
      }),
      defect_fields: [],
      has_defect: false,
      review_reason: "missing_value",
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(7400),
      updated_at: T(330),
    },
    attachments: [
      {
        original_filename: "email_038_SI.xlsx",
        content_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        size_bytes: 22118,
        doc_type: "SI",
      },
      {
        original_filename: "email_038_BL.docx",
        content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        size_bytes: 31004,
        doc_type: "BL",
      },
    ],
  },
  {
    // NEEDS_REVIEW — missing_attachment, and already reviewed once.
    record: {
      email_id: "email_045",
      sender: "ops@meridianshipmanagement.gr",
      subject: "Urgent: BL verification for OC 2XZP-01588 before vessel cut-off",
      body: "Mitchelle,\n\nWe need the BL for OC 2XZP-01588 verified today. The vessel closes at 18:00 local.\n\nI will forward the SI separately.\n\nDimitris Papadakis\nMeridian Ship Management SA",
      source_attachments: [],
      category: "BL_COMPARISON",
      status: "NEEDS_REVIEW",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: "missing_attachment",
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: T(480),
      reviewer_notes: "Chased the sender for both documents on 20 Sep. Awaiting reply.",
      created_at: T(9100),
      updated_at: T(480),
    },
    attachments: [],
  },
  {
    // completed, SI_REQUEST (no documents to compare).
    record: {
      email_id: "email_006",
      sender: "procurement@gulfpetrochem.bh",
      subject: "New shipping instruction required — PO 88214 — BASE OIL SN500",
      body: "Hello,\n\nWe need a shipping instruction raised for PO 88214, 2 x ISO tanks of base oil SN500, loading Bahrain to Mundra in the first week of October.\n\nPlease advise the format you need the details in.\n\nRegards,\nFatima Al Khalifa\nGulf Petrochem BSC",
      source_attachments: [],
      category: "SI_REQUEST",
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(2100),
      updated_at: T(64),
    },
    attachments: [],
  },
  {
    // completed, INVOICE_QUERY.
    record: {
      email_id: "email_016",
      sender: "ap.team@northstarretailgroup.co.uk",
      subject: "Query on invoice 4471182 — duplicate THC line",
      body: "Hi,\n\nInvoice 4471182 appears to charge terminal handling twice — once at origin and once under 'destination THC', but our contract is CFR.\n\nCould you review and issue a credit note if appropriate?\n\nThanks,\nHelen Cartwright\nAccounts Payable, Northstar Retail Group",
      source_attachments: ["attachments/email_016_INVOICE.pdf"],
      category: "INVOICE_QUERY",
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(3900),
      updated_at: T(150),
    },
    attachments: [
      { original_filename: "email_016_INVOICE.pdf", content_type: "application/pdf", size_bytes: 94210, doc_type: null },
    ],
  },
  {
    // completed, GENERAL.
    record: {
      email_id: "email_023",
      sender: "mitchelle.tan@averis.com",
      subject: "Out of office 24-26 September",
      body: "Hi team,\n\nI will be out of the office from Wednesday 24 September to Friday 26 September inclusive.\n\nFor anything urgent on documentation please contact Siti or Rehan.\n\nMitchelle",
      source_attachments: [],
      category: "GENERAL",
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(5400),
      updated_at: T(275),
    },
    attachments: [],
  },
  {
    // completed, SPAM.
    record: {
      email_id: "email_029",
      sender: "winner-notification@parcel-delivery-alerts.info",
      subject: "Your parcel is waiting — final notice — confirm customs fee now",
      body: "CONGRATULATIONS!\n\nYour package could not be delivered due to an unpaid customs charge of USD 2.90.\n\nConfirm your details within 24 hours to avoid return to sender.\n\nClick here to release your parcel.",
      source_attachments: [],
      category: "SPAM",
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(6100),
      updated_at: T(360),
    },
    attachments: [],
  },
  {
    // completed, BL_COMPARISON, nothing attached and nothing claimed —
    // the backend's clean pass-through (pipeline/run.py).
    record: {
      email_id: "email_041",
      sender: "chartering@baltictrampco.lv",
      subject: "Will send SI and BL tomorrow — OC 3MMK-00612",
      body: "Hi Mitchelle,\n\nJust a heads-up that the shipping instruction and draft BL for OC 3MMK-00612 will come across tomorrow morning once the shipper signs off.\n\nRegards,\nIlze Berzina\nBaltic Tramp Co SIA",
      source_attachments: [],
      category: "BL_COMPARISON",
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "rule",
      notes: "No attachments to compare.",
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(7800),
      updated_at: T(455),
    },
    attachments: [],
  },
  {
    // pending #1.
    record: {
      email_id: "email_052",
      sender: "exportdocs@rajasthanminerals.in",
      subject: "SI and BL draft — OC 7BBN-02901 — GYPSUM POWDER — 4x20GP",
      body: "Respected Madam,\n\nKindly find attached the shipping instruction and the draft bill of lading for OC 7BBN-02901.\n\nAwaiting your confirmation.\n\nThanking you,\nVikram Singh Rathore\nRajasthan Minerals & Chemicals Pvt Ltd",
      source_attachments: ["attachments/email_052_SI.txt", "attachments/email_052_BL.txt"],
      category: null,
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: null,
      notes: null,
      processing_status: "pending",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(45),
      updated_at: T(45),
    },
    attachments: [
      { original_filename: "email_052_SI.txt", content_type: "text/plain", size_bytes: 2901, doc_type: null },
      { original_filename: "email_052_BL.txt", content_type: "text/plain", size_bytes: 2755, doc_type: null },
    ],
  },
  {
    // pending #2.
    record: {
      email_id: "email_058",
      sender: "logistics@cascadiatimber.ca",
      subject: "Draft BL attached for OC 9QRS-01344 — SPRUCE LUMBER — 3x40HC",
      body: "Hello Mitchelle,\n\nPlease find the draft BL and our shipping instruction for OC 9QRS-01344.\n\nThe carrier needs confirmation by Tuesday.\n\nThank you,\nJanet Kowalski\nCascadia Timber Export Inc.",
      source_attachments: ["attachments/email_058_SI.pdf", "attachments/email_058_BL.pdf"],
      category: null,
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: null,
      notes: null,
      processing_status: "pending",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(28),
      updated_at: T(28),
    },
    attachments: [
      { original_filename: "email_058_SI.pdf", content_type: "application/pdf", size_bytes: 152440, doc_type: null },
      { original_filename: "email_058_BL.pdf", content_type: "application/pdf", size_bytes: 163770, doc_type: null },
    ],
  },
  {
    // pending #3.
    record: {
      email_id: "email_061",
      sender: "documentation@saharaagrotrade.eg",
      subject: "OC 5TTV-00276 — FROZEN STRAWBERRIES — documents attached",
      body: "Dear Sir/Madam,\n\nPlease find enclosed the shipping instruction and bill of lading draft for the above order.\n\nBest regards,\nAhmed Zaki\nSahara Agro Trade",
      source_attachments: ["attachments/email_061_SI.docx", "attachments/email_061_BL.docx"],
      category: null,
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: null,
      notes: null,
      processing_status: "pending",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(16),
      updated_at: T(16),
    },
    attachments: [
      {
        original_filename: "email_061_SI.docx",
        content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        size_bytes: 25880,
        doc_type: null,
      },
      {
        original_filename: "email_061_BL.docx",
        content_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        size_bytes: 26914,
        doc_type: null,
      },
    ],
  },
  {
    // processing.
    record: {
      email_id: "email_049",
      sender: "bl.desk@orientstarlines.sg",
      subject: "OC 8JKW-02055 — RUBBER SHEETS RSS3 — SI vs BL",
      body: "Hi,\n\nPlease verify the attached draft against the shipping instruction for OC 8JKW-02055.\n\nOrient Star Lines Pte Ltd\nBill of Lading Desk",
      source_attachments: ["attachments/email_049_SI.txt", "attachments/email_049_BL.pdf"],
      category: null,
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: null,
      notes: null,
      processing_status: "processing",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(9),
      updated_at: T(1),
    },
    attachments: [
      { original_filename: "email_049_SI.txt", content_type: "text/plain", size_bytes: 3011, doc_type: null },
      { original_filename: "email_049_BL.pdf", content_type: "application/pdf", size_bytes: 209884, doc_type: null },
    ],
  },
  {
    // failed.
    record: {
      email_id: "email_055",
      sender: "shipping@atlanticbulkcarriers.pt",
      subject: "OC 4ZZC-01799 — CEMENT CLINKER — SI + BL for checking",
      body: "Bom dia,\n\nAttached are the shipping instruction and the draft bill of lading for OC 4ZZC-01799.\n\nCumprimentos,\nJoao Ferreira\nAtlantic Bulk Carriers Lda",
      source_attachments: ["attachments/email_055_SI.pdf", "attachments/email_055_BL.pdf"],
      category: null,
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: null,
      notes: null,
      processing_status: "failed",
      retry_count: 2,
      last_error: "TimeoutError: processing failed",
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(700),
      updated_at: T(22),
    },
    attachments: [
      { original_filename: "email_055_SI.pdf", content_type: "application/pdf", size_bytes: 421330, doc_type: null },
      { original_filename: "email_055_BL.pdf", content_type: "application/pdf", size_bytes: 458812, doc_type: null },
    ],
  },
  {
    // completed + MISMATCH on weight only.
    record: {
      email_id: "email_063",
      sender: "docs@keralaspiceexports.in",
      subject: "OC 6WWR-00488 — BLACK PEPPER — weight discrepancy? please confirm",
      body: "Dear Mitchelle,\n\nAttached SI and BL for OC 6WWR-00488.\n\nThe carrier has used the verified gross mass from the weighbridge slip, which differs slightly from our declared figure.\n\nRegards,\nPriya Menon\nKerala Spice Exports",
      source_attachments: ["attachments/email_063_SI.txt", "attachments/email_063_BL.txt"],
      category: "BL_COMPARISON",
      status: "MISMATCH",
      si: fields({
        shipper: "KERALA SPICE EXPORTS PVT LTD",
        consignee: "EUROSPICE HANDELS GMBH",
        notify_party: "EUROSPICE HANDELS GMBH",
        port_of_loading: "COCHIN, INDIA (INCOK)",
        port_of_discharge: "HAMBURG, GERMANY (DEHAM)",
        container_count: 1,
        gross_weight_kg: 18240,
      }),
      bl: fields({
        shipper: "KERALA SPICE EXPORTS PVT LTD",
        consignee: "EUROSPICE HANDELS GMBH",
        notify_party: "EUROSPICE HANDELS GMBH",
        port_of_loading: "COCHIN, INDIA (INCOK)",
        port_of_discharge: "HAMBURG, GERMANY (DEHAM)",
        container_count: 1,
        gross_weight_kg: 18412.75,
      }),
      defect_fields: ["gross_weight_kg"],
      has_defect: true,
      review_reason: null,
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(8800),
      updated_at: T(520),
    },
    attachments: [
      { original_filename: "email_063_SI.txt", content_type: "text/plain", size_bytes: 2488, doc_type: "SI" },
      { original_filename: "email_063_BL.txt", content_type: "text/plain", size_bytes: 2501, doc_type: "BL" },
    ],
  },
  {
    // completed + OK.
    record: {
      email_id: "email_070",
      sender: "export@vietnamtextilegroup.vn",
      subject: "OC 1HHM-03052 — COTTON YARN 30S — SI and BL enclosed",
      body: "Dear Mitchelle,\n\nEnclosed please find the shipping instruction and the draft bill of lading for OC 1HHM-03052.\n\nWe confirm no changes from the previous booking.\n\nBest regards,\nNguyen Thi Lan\nVietnam Textile Group JSC",
      source_attachments: ["attachments/email_070_SI.txt", "attachments/email_070_BL.txt"],
      category: "BL_COMPARISON",
      status: "OK",
      si: fields({
        shipper: "VIETNAM TEXTILE GROUP JSC",
        consignee: "ISTANBUL YARN IMPORT A.S.",
        notify_party: "ISTANBUL YARN IMPORT A.S.",
        port_of_loading: "HAI PHONG, VIETNAM (VNHPH)",
        port_of_discharge: "AMBARLI, TURKEY (TRAMB)",
        container_count: 2,
        gross_weight_kg: 43600,
      }),
      bl: fields({
        shipper: "VIETNAM TEXTILE GROUP JSC",
        consignee: "ISTANBUL YARN IMPORT A.S.",
        notify_party: "ISTANBUL YARN IMPORT A.S.",
        port_of_loading: "HAI PHONG, VIETNAM (VNHPH)",
        port_of_discharge: "AMBARLI, TURKEY (TRAMB)",
        container_count: 2,
        gross_weight_kg: 43600,
      }),
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "rule",
      notes: "No mismatch detected.",
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(10200),
      updated_at: T(640),
    },
    attachments: [
      { original_filename: "email_070_SI.txt", content_type: "text/plain", size_bytes: 2650, doc_type: "SI" },
      { original_filename: "email_070_BL.txt", content_type: "text/plain", size_bytes: 2644, doc_type: "BL" },
    ],
  },
  {
    // completed, SI_REQUEST #2.
    record: {
      email_id: "email_074",
      sender: "supplychain@pampasbeef.ar",
      subject: "Please raise SI for OC 2VVN-01623 — FROZEN BEEF — 6x40RH",
      body: "Hola Mitchelle,\n\nCould you please raise the shipping instruction for OC 2VVN-01623? Six reefer containers, Buenos Aires to Shanghai, temperature -18C.\n\nThe booking reference from the carrier is MSCU8841203.\n\nGracias,\nMartin Giordano\nPampas Beef SA",
      source_attachments: [],
      category: "SI_REQUEST",
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "llm",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(11000),
      updated_at: T(720),
    },
    attachments: [],
  },
  {
    // completed + MISMATCH on port_of_loading.
    record: {
      email_id: "email_081",
      sender: "bl@maritimadelnorte.es",
      subject: "OC 8CCF-00195 — CERAMIC TILES — BL draft vs SI — please confirm POL",
      body: "Buenos dias Mitchelle,\n\nAdjuntamos la SI y el borrador del BL para OC 8CCF-00195.\n\nEl transportista ha cambiado el puerto de carga. Por favor confirmar.\n\nUn saludo,\nElena Ruiz\nMaritima del Norte SL",
      source_attachments: ["attachments/email_081_SI.xlsx", "attachments/email_081_BL.pdf"],
      category: "BL_COMPARISON",
      status: "MISMATCH",
      si: fields({
        shipper: "CERAMICA CASTELLON SA",
        consignee: "GULF BUILDING MATERIALS LLC",
        notify_party: "GULF BUILDING MATERIALS LLC",
        port_of_loading: "VALENCIA, SPAIN (ESVLC)",
        port_of_discharge: "DAMMAM, SAUDI ARABIA (SADMM)",
        container_count: 8,
        gross_weight_kg: 196400,
      }),
      bl: fields({
        shipper: "CERAMICA CASTELLON SA",
        consignee: "GULF BUILDING MATERIALS LLC",
        notify_party: "GULF BUILDING MATERIALS LLC",
        port_of_loading: "BARCELONA, SPAIN (ESBCN)",
        port_of_discharge: "DAMMAM, SAUDI ARABIA (SADMM)",
        container_count: 8,
        gross_weight_kg: 196400,
      }),
      defect_fields: ["port_of_loading"],
      has_defect: true,
      review_reason: null,
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(12100),
      updated_at: T(810),
    },
    attachments: [
      {
        original_filename: "email_081_SI.xlsx",
        content_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        size_bytes: 19822,
        doc_type: "SI",
      },
      { original_filename: "email_081_BL.pdf", content_type: "application/pdf", size_bytes: 288140, doc_type: "BL" },
    ],
  },
  {
    // completed, INVOICE_QUERY #2.
    record: {
      email_id: "email_088",
      sender: "finance@scandiaimports.se",
      subject: "Credit note request — invoice 4468920 — demurrage charged in error",
      body: "Hello,\n\nWe have been invoiced four days of demurrage on invoice 4468920, but the containers were released on the second free day.\n\nThe terminal gate-out records are attached.\n\nRegards,\nErik Lindqvist\nScandia Imports AB",
      source_attachments: ["attachments/email_088_GATEOUT.xlsx"],
      category: "INVOICE_QUERY",
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "rule",
      notes: null,
      processing_status: "completed",
      retry_count: 0,
      last_error: null,
      reviewed_at: null,
      reviewer_notes: null,
      created_at: T(13400),
      updated_at: T(905),
    },
    attachments: [
      {
        original_filename: "email_088_GATEOUT.xlsx",
        content_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        size_bytes: 15330,
        doc_type: null,
      },
    ],
  },
];

const BASE_EMAILS: EmailRecord[] = SEEDS.map((seed) => seed.record);

export const MOCK_ATTACHMENTS: AttachmentRecord[] = SEEDS.flatMap((seed) =>
  seed.attachments.map((attachment, index) => ({
    id: `${seed.record.email_id}-att-${index + 1}`,
    email_id: seed.record.email_id,
    doc_type: attachment.doc_type,
    storage_bucket: "documents",
    // Canonical convention from PROJECT_RULES.md §14: {email_id}/{original_filename}
    storage_path: `${seed.record.email_id}/${attachment.original_filename}`,
    original_filename: attachment.original_filename,
    content_type: attachment.content_type,
    size_bytes: attachment.size_bytes,
    created_at: seed.record.created_at,
  })),
);

/**
 * Result the demo layer hands back when a `pending` email is processed.
 * These are pre-written outcomes, not computed ones.
 */
export const MOCK_PROCESS_OUTCOMES: Record<
  string,
  Pick<
    EmailRecord,
    "category" | "status" | "si" | "bl" | "defect_fields" | "has_defect" | "review_reason" | "decided_by" | "notes"
  >
> = {
  email_052: {
    category: "BL_COMPARISON",
    status: "MISMATCH",
    si: fields({
      shipper: "RAJASTHAN MINERALS & CHEMICALS PVT LTD",
      consignee: "AL FALAH BUILDING SUPPLIES LLC",
      notify_party: "AL FALAH BUILDING SUPPLIES LLC",
      port_of_loading: "MUNDRA, INDIA (INMUN)",
      port_of_discharge: "SOHAR, OMAN (OMSOH)",
      container_count: 4,
      gross_weight_kg: 96800,
    }),
    bl: fields({
      shipper: "RAJASTHAN MINERALS & CHEMICALS PVT LTD",
      consignee: "AL FALAH BUILDING SUPPLIES LLC",
      notify_party: "AL FALAH BUILDING SUPPLIES LLC",
      port_of_loading: "MUNDRA, INDIA (INMUN)",
      port_of_discharge: "SOHAR, OMAN (OMSOH)",
      container_count: 4,
      gross_weight_kg: 98150,
    }),
    defect_fields: ["gross_weight_kg"],
    has_defect: true,
    review_reason: null,
    decided_by: "rule",
    notes: null,
  },
  email_058: {
    category: "BL_COMPARISON",
    status: "OK",
    si: fields({
      shipper: "CASCADIA TIMBER EXPORT INC",
      consignee: "OSAKA WOOD TRADING KK",
      notify_party: "OSAKA WOOD TRADING KK",
      port_of_loading: "VANCOUVER, CANADA (CAVAN)",
      port_of_discharge: "OSAKA, JAPAN (JPOSA)",
      container_count: 3,
      gross_weight_kg: 71250,
    }),
    bl: fields({
      shipper: "CASCADIA TIMBER EXPORT INC.",
      consignee: "OSAKA WOOD TRADING KK",
      notify_party: "OSAKA WOOD TRADING KK",
      port_of_loading: "VANCOUVER, CANADA (CAVAN)",
      port_of_discharge: "OSAKA, JAPAN (JPOSA)",
      container_count: 3,
      gross_weight_kg: 71250,
    }),
    defect_fields: [],
    has_defect: false,
    review_reason: null,
    decided_by: "rule",
    notes: "No mismatch detected.",
  },
  email_061: {
    category: "BL_COMPARISON",
    status: "NEEDS_REVIEW",
    si: fields({
      shipper: "SAHARA AGRO TRADE",
      consignee: "BERLIN FROZEN FOODS GMBH",
      notify_party: "BERLIN FROZEN FOODS GMBH",
      port_of_loading: "ALEXANDRIA, EGYPT (EGALY)",
      port_of_discharge: "BREMERHAVEN, GERMANY (DEBRV)",
      container_count: null,
      gross_weight_kg: 28900,
    }),
    bl: fields({
      shipper: "SAHARA AGRO TRADE",
      consignee: "BERLIN FROZEN FOODS GMBH",
      notify_party: "BERLIN FROZEN FOODS GMBH",
      port_of_loading: "ALEXANDRIA, EGYPT (EGALY)",
      port_of_discharge: "BREMERHAVEN, GERMANY (DEBRV)",
      container_count: 2,
      gross_weight_kg: 28900,
    }),
    defect_fields: [],
    has_defect: false,
    review_reason: "missing_value",
    decided_by: "rule",
    notes: null,
  },
  email_049: {
    category: "BL_COMPARISON",
    status: "OK",
    si: fields({
      shipper: "ORIENT STAR LINES PTE LTD",
      consignee: "AKRON RUBBER PROCESSING INC",
      notify_party: "AKRON RUBBER PROCESSING INC",
      port_of_loading: "SINGAPORE (SGSIN)",
      port_of_discharge: "SAVANNAH, USA (USSAV)",
      container_count: 2,
      gross_weight_kg: 40120,
    }),
    bl: fields({
      shipper: "ORIENT STAR LINES PTE LTD",
      consignee: "AKRON RUBBER PROCESSING INC",
      notify_party: "AKRON RUBBER PROCESSING INC",
      port_of_loading: "SINGAPORE (SGSIN)",
      port_of_discharge: "SAVANNAH, USA (USSAV)",
      container_count: 2,
      gross_weight_kg: 40120,
    }),
    defect_fields: [],
    has_defect: false,
    review_reason: null,
    decided_by: "rule",
    notes: "No mismatch detected.",
  },
  // The failed email succeeds when retried.
  email_055: {
    category: "BL_COMPARISON",
    status: "MISMATCH",
    si: fields({
      shipper: "ATLANTIC BULK CARRIERS LDA",
      consignee: "CASABLANCA CEMENT SARL",
      notify_party: "CASABLANCA CEMENT SARL",
      port_of_loading: "LISBON, PORTUGAL (PTLIS)",
      port_of_discharge: "CASABLANCA, MOROCCO (MACAS)",
      container_count: 12,
      gross_weight_kg: 298400,
    }),
    bl: fields({
      shipper: "ATLANTIC BULK CARRIERS LDA",
      consignee: "CASABLANCA CEMENT SARL",
      notify_party: "OCP GROUP SA",
      port_of_loading: "LISBON, PORTUGAL (PTLIS)",
      port_of_discharge: "CASABLANCA, MOROCCO (MACAS)",
      container_count: 12,
      gross_weight_kg: 298400,
    }),
    defect_fields: ["notify_party"],
    has_defect: true,
    review_reason: null,
    decided_by: "rule",
    notes: null,
  },
};

/** Stand-in outcome for an email the demo layer has no script for. */
export const MOCK_DEFAULT_OUTCOME = MOCK_PROCESS_OUTCOMES.email_058!;



/* ------------------------------------------------------------------ *
 * Batch fixtures
 * ------------------------------------------------------------------
 * A batch-processed email is stored under a synthetic, batch-namespaced
 * email_id with the organizer's real id kept in original_email_id — see
 * schema.sql's batch migration note on feature/export-upload.
 * ------------------------------------------------------------------ */

export const MOCK_BATCH_ID = "batch_3f9a1c2e7b10";

const BATCH_SEEDS: Array<{
  original: string;
  sender: string;
  subject: string;
  outcome: Pick<
    EmailRecord,
    "category" | "status" | "si" | "bl" | "defect_fields" | "has_defect" | "review_reason" | "decided_by" | "notes"
  >;
}> = [
  {
    original: "email_004",
    sender: "docs@vitalsolutions.sg",
    subject: "REQUEST BL DRAFT _ PO 26067_ COATED IVORY BOARD__138MT",
    outcome: {
      category: "BL_COMPARISON",
      status: "MISMATCH",
      si: fields({
        shipper: "APRIL FAR EAST (M) SDN BHD",
        consignee: "EAST BRIGHT FZ-LLC",
        notify_party: "EAST BRIGHT FZ-LLC",
        port_of_loading: "NANTONG, CHINA (CNNTG)",
        port_of_discharge: "KARACHI, PAKISTAN (PKKHI)",
        container_count: 6,
        gross_weight_kg: 131058,
      }),
      bl: fields({
        shipper: "APRIL FAR EAST (M) SDN BHD",
        consignee: "UAB NOVAKOPA",
        notify_party: "UAB NOVAKOPA",
        port_of_loading: "NANTONG, CHINA (CNNTG)",
        port_of_discharge: "KARACHI, PAKISTAN (PKKHI)",
        container_count: 6,
        gross_weight_kg: 131058,
      }),
      defect_fields: ["consignee", "notify_party"],
      has_defect: true,
      review_reason: null,
      decided_by: "rule",
      notes: null,
    },
  },
  {
    original: "email_012",
    sender: "shipping@nordicpulp.no",
    subject: "OC 4PPL-00921 — NBSK PULP — SI and BL attached",
    outcome: {
      category: "BL_COMPARISON",
      status: "OK",
      si: fields({
        shipper: "NORDIC PULP AS",
        consignee: "GUANGZHOU PAPER GROUP CO LTD",
        notify_party: "GUANGZHOU PAPER GROUP CO LTD",
        port_of_loading: "OSLO, NORWAY (NOOSL)",
        port_of_discharge: "GUANGZHOU, CHINA (CNGZG)",
        container_count: 7,
        gross_weight_kg: 158900,
      }),
      bl: fields({
        shipper: "NORDIC PULP AS",
        consignee: "GUANGZHOU PAPER GROUP CO LTD",
        notify_party: "GUANGZHOU PAPER GROUP CO LTD",
        port_of_loading: "OSLO, NORWAY (NOOSL)",
        port_of_discharge: "GUANGZHOU, CHINA (CNGZG)",
        container_count: 7,
        gross_weight_kg: 158900,
      }),
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "rule",
      notes: "No mismatch detected.",
    },
  },
  {
    original: "email_018",
    sender: "ops@tridentmarine.ph",
    subject: "OC 6BBV-01077 — COCONUT OIL — BL check",
    outcome: {
      category: "BL_COMPARISON",
      status: "NEEDS_REVIEW",
      si: fields({
        shipper: "TRIDENT MARINE SERVICES INC",
        consignee: "ROTTERDAM OILS BV",
        notify_party: null,
        port_of_loading: "MANILA, PHILIPPINES (PHMNL)",
        port_of_discharge: "ROTTERDAM, NETHERLANDS (NLRTM)",
        container_count: 3,
        gross_weight_kg: null,
      }),
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: "missing_attachment",
      decided_by: "rule",
      notes: null,
    },
  },
  {
    original: "email_025",
    sender: "exports@andesmining.pe",
    subject: "OC 9NNX-02180 — ZINC CONCENTRATE — documents for checking",
    outcome: {
      category: "BL_COMPARISON",
      status: "MISMATCH",
      si: fields({
        shipper: "ANDES MINING SAC",
        consignee: "NYRSTAR BUDEL BV",
        notify_party: "NYRSTAR BUDEL BV",
        port_of_loading: "CALLAO, PERU (PECLL)",
        port_of_discharge: "ANTWERP, BELGIUM (BEANR)",
        container_count: 10,
        gross_weight_kg: 248000,
      }),
      bl: fields({
        shipper: "ANDES MINING SAC",
        consignee: "NYRSTAR BUDEL BV",
        notify_party: "NYRSTAR BUDEL BV",
        port_of_loading: "CALLAO, PERU (PECLL)",
        port_of_discharge: "ANTWERP, BELGIUM (BEANR)",
        container_count: 10,
        gross_weight_kg: 251400,
      }),
      defect_fields: ["gross_weight_kg"],
      has_defect: true,
      review_reason: null,
      decided_by: "rule",
      notes: null,
    },
  },
  {
    original: "email_031",
    sender: "billing@lagosfreight.ng",
    subject: "Invoice 88210 — query on bunker adjustment factor",
    outcome: {
      category: "INVOICE_QUERY",
      status: "OK",
      si: null,
      bl: null,
      defect_fields: [],
      has_defect: false,
      review_reason: null,
      decided_by: "rule",
      notes: null,
    },
  },
];

function batchRecord(batchId: string, index: number): EmailRecord {
  const seed = BATCH_SEEDS[index % BATCH_SEEDS.length]!;
  const suffix = index < BATCH_SEEDS.length ? "" : `_${Math.floor(index / BATCH_SEEDS.length)}`;
  const original = `${seed.original}${suffix}`;
  const created = T(1200 + index * 3);
  return {
    email_id: `${batchId}__${original}`,
    sender: seed.sender,
    subject: seed.subject,
    body: `Imported from an organizer bundle (${original}).`,
    source_attachments: [`attachments/${original}_SI.txt`, `attachments/${original}_BL.txt`],
    ...seed.outcome,
    processing_status: "completed",
    retry_count: 0,
    last_error: null,
    reviewed_at: null,
    reviewer_notes: null,
    created_at: created,
    updated_at: created,
    batch_id: batchId,
    original_email_id: original,
  };
}

/** The batch that already exists in the demo dataset. */
export const MOCK_BATCH_EMAILS: EmailRecord[] = BATCH_SEEDS.map((_, index) =>
  batchRecord(MOCK_BATCH_ID, index),
);

/** Builds the emails a freshly uploaded demo bundle produces. */
export function makeMockBatchEmails(batchId: string, count: number): EmailRecord[] {
  return Array.from({ length: count }, (_, index) => batchRecord(batchId, index));
}

export const MOCK_BATCH: Batch = {
  batch_id: MOCK_BATCH_ID,
  total: MOCK_BATCH_EMAILS.length,
  done: MOCK_BATCH_EMAILS.length,
  failed: 0,
  status: "completed",
  created_at: T(1260),
  finished_at: T(1200),
};

/** Everything the demo layer serves: hand-written records plus one batch. */
export const MOCK_EMAILS: EmailRecord[] = [...BASE_EMAILS, ...MOCK_BATCH_EMAILS];
